"""
core/settlement/turn_engine.py
Pure functions for the Settlement Turns Economy:
  - Zeal earning / daily-cap logic
  - Development Turn conversion
  - Next Turn processing (projects, deals, passive zeal, events)
  - Black Market value calculation, turn cost, reward rolling
  - Event checking and trigger logic
"""

from __future__ import annotations

import math
import random
from typing import TYPE_CHECKING

from core.emojis import GOLD_COIN
from core.hall_of_firsts import triggers as hof_triggers
from core.settlement.constants import (
    BM_BASE_LOOT_WEIGHTS,
    BM_GOLD_MAX,
    BM_GOLD_MIN,
    BM_ITEM_VALUES,
    BM_ROLLS_PER_VALUE,
    BM_TREE_NODES,
    BM_TURNS_HALF_SATURATION,
    BM_TURNS_MAX,
    BM_TURNS_MIN,
    BM_TURNS_SCALE_START,
    IDLEM_PER_TURN_BASE,
    PASSIVE_ZEAL_PER_HOUR_BASE,
    PROJECT_CONSTRUCTION_DT,
    SETTLEMENT_EVENTS,
    WORKERS_PER_TURN_BASE,
    ZEAL_DAILY_HARD_CAP,
    ZEAL_DAILY_SOFT_CAP,
    ZEAL_TO_DT,
)

if TYPE_CHECKING:
    pass


# ---------------------------------------------------------------------------
# Zeal economy
# ---------------------------------------------------------------------------


def compute_zeal_gain(base: int, earned_today: int) -> int:
    """
    Returns the actual Zeal that should be credited, applying the soft/hard cap.

    - Below ZEAL_DAILY_SOFT_CAP: full amount.
    - Between soft and hard cap: halved.
    - Above ZEAL_DAILY_HARD_CAP: nothing.
    """
    if earned_today >= ZEAL_DAILY_HARD_CAP:
        return 0
    remaining_to_hard = ZEAL_DAILY_HARD_CAP - earned_today
    remaining_to_soft = max(0, ZEAL_DAILY_SOFT_CAP - earned_today)

    full_portion = min(base, remaining_to_soft)
    halved_portion = min(base - full_portion, remaining_to_hard - full_portion)

    return full_portion + (halved_portion // 2)


def passive_zeal_for_period(hours: float, town_hall_tier: int) -> int:
    """Passive Zeal generated by the settlement over a given number of hours.
    T1 ≈ 4/hr, scaling linearly to ~40/hr at T7."""
    rate = PASSIVE_ZEAL_PER_HOUR_BASE + (town_hall_tier - 1) * 6
    return int(hours * rate)


# ---------------------------------------------------------------------------
# Project DT costs
# ---------------------------------------------------------------------------


def construction_dt_cost(building_type: str, event_effects: dict | None = None) -> int:
    base = PROJECT_CONSTRUCTION_DT.get(building_type, 12)
    if event_effects and event_effects.get("construction_dt_halved"):
        base = max(1, base // 2)
    if event_effects and event_effects.get("construction_dt_surcharge"):
        base = int(base * 1.5)
    return base


_UPGRADE_DT_TABLE = {2: 5, 3: 10, 4: 25, 5: 50}
_UBER_SHRINE_UPGRADE_DT = {2: 25, 3: 50, 4: 100, 5: 200}


def upgrade_dt_cost(
    building_type: str, target_tier: int, event_effects: dict | None = None
) -> int:
    if building_type == "uber_shrine":
        base = _UBER_SHRINE_UPGRADE_DT.get(target_tier, 200)
    else:
        base = max(1, _UPGRADE_DT_TABLE.get(target_tier, 50))
    if event_effects and event_effects.get("construction_dt_halved"):
        base = max(1, base // 2)
    if event_effects and event_effects.get("construction_dt_surcharge"):
        base = int(base * 1.5)
    return base


def meta_construction_dt_cost(
    building_type: str, event_effects: dict | None = None
) -> int:
    """DT cost to construct a meta building = gold_cost // 1000, minimum 1."""
    from core.settlement.plots import META_BUILDINGS

    gold = META_BUILDINGS.get(building_type, {}).get("cost", {}).get("gold", 10_000)
    base = max(1, gold // 1000)
    if event_effects and event_effects.get("construction_dt_halved"):
        base = max(1, base // 2)
    if event_effects and event_effects.get("construction_dt_surcharge"):
        base = int(base * 1.5)
    return base


# ---------------------------------------------------------------------------
# Next Turn processor
# ---------------------------------------------------------------------------


async def process_next_turn(
    bot,
    user_id: str,
    server_id: str,
    town_hall_tier: int,
) -> dict:
    """
    Processes one Development Turn. Returns a summary dict with keys:
      - turns_gained: int
      - zeal_spent: int
      - projects_completed: list[dict]
      - deal_completed: dict | None  (the deal if it finished this turn)
      - deal_rewards: dict | None    (granted rewards if deal completed)
      - events_fired: list[str]      (event names that fired)
      - events_expired: list[str]
      - workers_from_nursery: int
      - idlem_from_foundry: int
    """
    summary: dict = {
        "turns_gained": 1,
        "zeal_spent": ZEAL_TO_DT,
        "projects_completed": [],
        "deal_completed": None,
        "deal_rewards": None,
        "events_fired": [],
        "crisis_events_fired": [],
        "events_expired": [],
        "workers_from_nursery": 0,
        "nursery_ideology": "",
        "idlem_from_foundry": 0,
        "dt_resources": {},
    }

    # 1. Read active ongoing events BEFORE advancing projects so their multipliers
    #    apply to any projects that complete this turn.
    active_events = await bot.database.settlement.get_active_events(user_id, server_id)
    event_effects: dict = {}
    for _ev in active_events:
        _ev_def = SETTLEMENT_EVENTS.get(_ev.get("event_key", ""), {})
        _ev_data = _ev.get("data", {})
        for _k, _v in _ev_def.get("effects", {}).items():
            if _k not in event_effects:
                event_effects[_k] = _resolve_band(_v, _ev_data)

    # 2. Advance all projects; collect completed ones
    completed = await bot.database.settlement.advance_projects(user_id, server_id)
    for proj in completed:
        result = await _complete_project(bot, user_id, server_id, proj, event_effects)
        await bot.database.settlement.delete_project(proj["id"])
        summary["projects_completed"].append(
            {
                "type": proj["project_type"],
                "label": result.get("label", proj["project_type"]),
                "is_meta": result.get("is_meta", False),
            }
        )
        if proj["project_type"] == "foundry_idlem":
            summary["idlem_from_foundry"] += result.get("idlem", 0)

    # 2b. Nursery: automatically produce workers each DT if staffed
    nursery_building = await bot.database.settlement.get_building_by_type(
        user_id, server_id, "nursery"
    )
    if (
        nursery_building
        and nursery_building.workers_assigned > 0
        and not nursery_building.is_disabled
    ):
        nursery_mult = event_effects.get("nursery_mult", 1.0)
        workers = int(
            WORKERS_PER_TURN_BASE
            * (nursery_building.workers_assigned / 100)
            * nursery_mult
        )
        workers += random.randint(0, 1)
        user_row = await bot.database.users.get(user_id, server_id)
        ideology_name = (user_row["ideology"] or "") if user_row else ""
        if ideology_name:
            current = await bot.database.social.get_follower_count(ideology_name)
            new_total = current + workers
            await bot.database.social.update_followers(ideology_name, new_total)
            await hof_triggers.check_cult_leader(bot, user_id, new_total)
        summary["workers_from_nursery"] = workers
        summary["nursery_ideology"] = ideology_name

    # 2c. Idlem Foundry: automatically produce Idlem each DT if staffed
    foundry_building = await bot.database.settlement.get_building_by_type(
        user_id, server_id, "idlem_foundry"
    )
    if (
        foundry_building
        and foundry_building.workers_assigned > 0
        and not foundry_building.is_disabled
    ):
        idlem_mult = event_effects.get("idlem_mult", 1.0)
        idlem = int(
            IDLEM_PER_TURN_BASE * (foundry_building.workers_assigned / 100) * idlem_mult
        )
        idlem += random.randint(0, 1)
        await bot.database.settlement.add_idlem(user_id, server_id, idlem)
        summary["idlem_from_foundry"] += idlem

    # 3. Advance pending Black Market deal
    deal = await bot.database.settlement.get_pending_deal(user_id, server_id)
    if deal:
        deal = await bot.database.settlement.decrement_deal_turn(user_id, server_id)
        if deal and deal["turns_remaining"] <= 0:
            # Deal complete — roll rewards
            user_row = await bot.database.users.get(user_id, server_id)
            player_level = user_row["level"] if user_row else 1
            deal_tree_nodes = await bot.database.settlement.get_bm_tree(
                user_id, server_id
            )
            from core.settlement.bm_log import BMLogger

            bm_log = BMLogger(user_id, deal["total_value"], 0)
            bm_log.log_tree(deal_tree_nodes, deal.get("active_biases", []))
            rewards = roll_bm_rewards(
                deal["total_value"],
                deal["active_biases"],
                player_level,
                tree_nodes=deal_tree_nodes,
                bm_logger=bm_log,
            )
            bm_log.close()
            # Atomic: a crash between granting and deleting would re-grant the
            # deal on the next turn.
            async with bot.database.transaction():
                await _grant_bm_rewards(bot, user_id, server_id, rewards)
                await bot.database.settlement.delete_pending_deal(user_id, server_id)
            summary["deal_completed"] = deal
            summary["deal_rewards"] = rewards

    # 4. Tick events
    newly_fired, expired = await bot.database.settlement.tick_events(user_id, server_id)
    for ev in expired:
        await bot.database.settlement.remove_event(ev["id"])
        summary["events_expired"].append(
            SETTLEMENT_EVENTS.get(ev["event_key"], {}).get("name", ev["event_key"])
        )

    for ev in newly_fired:
        ev_def = SETTLEMENT_EVENTS.get(ev["event_key"], {})
        ev_data = ev.get("data", {})
        fx_result = await _apply_event_effects(bot, user_id, server_id, ev_def, ev_data)
        # Convert upcoming → ongoing if it has duration; carry over ev_data so band values persist
        dur = ev_data.get("duration", ev_def.get("duration_turns", 0))
        if dur > 0:
            await bot.database.settlement.add_event(
                user_id,
                server_id,
                ev["event_key"],
                "ongoing",
                turns_until=0,
                turns_remaining=dur,
                data=ev_data if ev_data else None,
            )
        await bot.database.settlement.remove_event(ev["id"])
        ev_name = ev_def.get("name", ev["event_key"])
        if fx_result.get("zeal_granted"):
            _zg = fx_result["zeal_granted"]
            ev_name = f"{ev_name} ({'+' if _zg >= 0 else ''}{_zg} Zeal)"
        if ev_def.get("effects", {}).get("spawn_combat"):
            entry: dict = {"name": ev_name}
            if fx_result.get("plague_losses"):
                entry["plague_losses"] = fx_result["plague_losses"]
            summary["crisis_events_fired"].append(entry)
        else:
            summary["events_fired"].append(ev_name)

    # 5. Increment total turns
    await bot.database.settlement.increment_turns(user_id, server_id)
    turns_data = await bot.database.settlement.get_turns_data(user_id, server_id)
    new_total = turns_data["total_development_turns"]

    # 6. Check for new events to schedule
    await _check_schedule_events(bot, user_id, server_id, new_total)

    # 7. DT-based resource production (generators + converters at 5× hourly rate)
    (
        dt_changes,
        market_gold,
        war_camp_stamina,
        companion_cookie,
    ) = await _calculate_dt_production(bot, user_id, server_id)
    if dt_changes:
        # Snapshot resources BEFORE commit_production pops "timber"/"stone" from the dict.
        summary["dt_resources"] = {k: v for k, v in dt_changes.items() if v > 0}
        await bot.database.settlement.commit_production(user_id, server_id, dt_changes)
    if market_gold > 0:
        await bot.database.users.modify_gold(user_id, market_gold)
        summary["dt_resources"]["market_gold"] = market_gold
    if war_camp_stamina > 0:
        await bot.database.users.add_stamina_capped(user_id, war_camp_stamina)
        summary["dt_resources"]["war_camp_stamina"] = war_camp_stamina
    if companion_cookie > 0:
        summary["dt_resources"]["companion_xp"] = companion_cookie
        await bot.database.users.modify_currency(
            user_id, "companion_pet_xp", companion_cookie
        )

    return summary


async def _calculate_dt_production(
    bot, user_id: str, server_id: str
) -> tuple[dict, int, int, int]:
    """
    Calculates per-DT resource output for all active generator and converter buildings.
    Rate = 5× the base hourly rate (i.e. equivalent to 5 hours of passive generation).

    Returns (changes_dict, market_gold, war_camp_stamina, companion_cookie_xp).
    Does NOT include Nursery or Idlem Foundry — those are handled via projects.
    """
    from core.settlement.mechanics import SettlementMechanics

    settlement = await bot.database.settlement.get_settlement(user_id, server_id)
    if not settlement or not settlement.buildings:
        return {}, 0, 0, 0

    # Fetch raw inventories for converters
    try:
        mining = await bot.database.skills.get_data(user_id, server_id, "mining")
        wood = await bot.database.skills.get_data(user_id, server_id, "woodcutting")
        fish = await bot.database.skills.get_data(user_id, server_id, "fishing")
        raw_inv = {
            "iron_ore": mining["iron_ore"],
            "coal_ore": mining["coal_ore"],
            "gold_ore": mining["gold_ore"],
            "platinum_ore": mining["platinum_ore"],
            "idea_ore": mining["idea_ore"],
            "oak_logs": wood["oak_logs"],
            "willow_logs": wood["willow_logs"],
            "mahogany_logs": wood["mahogany_logs"],
            "magic_logs": wood["magic_logs"],
            "idea_logs": wood["idea_logs"],
            "desiccated_bones": fish["desiccated_bones"],
            "regular_bones": fish["regular_bones"],
            "sturdy_bones": fish["sturdy_bones"],
            "reinforced_bones": fish["reinforced_bones"],
            "titanium_bones": fish["titanium_bones"],
        }
    except Exception:
        raw_inv = {}

    _DT_HOURS = 5.0  # 1 DT = 5× hourly rate
    # Market is a pure passive generator (real-time hourly accrual only via Collect) —
    # it does not additionally receive the per-DT burst other hybrid buildings get.
    _SKIP = {
        "nursery",
        "idlem_foundry",
        "black_market",
        "hatchery",
        "war_camp",
        "market",
    }

    # Adjacency bonuses from meta buildings (Servant's Quarters, Supply Depot, etc.)
    from core.settlement.models import Plot as PlotModel

    try:
        _plot_rows = await bot.database.plots.get_plots(user_id, server_id)
        plots = [
            PlotModel(
                plot_index=r["plot_index"],
                is_developed=bool(r["is_developed"]),
                bonus_type=r["bonus_type"],
            )
            for r in _plot_rows
        ]
    except Exception:
        plots = []
    adj_bonuses = SettlementMechanics.calculate_adjacency_bonuses(
        plots, settlement.buildings
    )

    # Build a plot_index → bonus_type lookup for plot terrain bonuses
    plot_bonus_map: dict[int, str | None] = (
        {p.plot_index: p.bonus_type for p in plots} if plots else {}
    )

    # Mastery converter output bonus (Master Quarry / Seasoned Timber synergy nodes)
    refining_bonus = 0.0
    try:
        mastery_row = await bot.database.skills.get_mastery(user_id, server_id)
        if mastery_row:
            from core.skills.mastery import has_master_quarry, has_seasoned_timber

            if has_master_quarry(mastery_row):
                refining_bonus += 0.10
            if has_seasoned_timber(mastery_row):
                refining_bonus += 0.10
    except Exception:
        pass

    # Extract event production bonuses/penalties for this turn.
    _active_evs = await bot.database.settlement.get_active_events(user_id, server_id)
    _dt_gen_bonus = 0.0
    _dt_conv_bonus = 0.0
    _dt_market_gold_bonus = 0.0
    for _ev in _active_evs:
        _ev_def = SETTLEMENT_EVENTS.get(_ev.get("event_key", ""), {})
        _ev_data = _ev.get("data", {})
        _effs = _ev_def.get("effects", {})
        _dt_gen_bonus += (
            _resolve_band(_effs.get("generator_bonus", 0.0), _ev_data)
            if "generator_bonus" in _effs
            else 0.0
        )
        _dt_conv_bonus += (
            _resolve_band(_effs.get("converter_bonus", 0.0), _ev_data)
            if "converter_bonus" in _effs
            else 0.0
        )
        _dt_market_gold_bonus += (
            _resolve_band(_effs.get("market_gold_bonus", 0.0), _ev_data)
            if "market_gold_bonus" in _effs
            else 0.0
        )

    total_changes: dict = {}
    market_gold = 0
    war_camp_stamina = 0
    companion_cookie = 0

    for b in settlement.buildings:
        if (
            b.is_meta
            or b.is_disabled
            or b.building_type in _SKIP
            or b.workers_assigned <= 0
        ):
            continue
        b_def = SettlementMechanics.BUILDINGS.get(b.building_type)
        if not b_def or b_def["type"] not in ("generator", "converter"):
            continue

        adj = adj_bonuses.get(b.plot_index, {}) if b.plot_index is not None else {}
        plot_bonus = (
            plot_bonus_map.get(b.plot_index) if b.plot_index is not None else None
        )

        changes = SettlementMechanics.calculate_production(
            building_type=b.building_type,
            tier=b.tier,
            workers=b.workers_assigned,
            hours_elapsed=_DT_HOURS,
            raw_inventory=dict(raw_inv),  # copy so converter deductions don't bleed
            plot_bonus_type=plot_bonus,
            adj_production_mult=adj.get("production_mult", 0.0),
            adj_converter_mult=adj.get("converter_mult", 0.0),
            mastery_converter_output_mult=refining_bonus,
            event_generator_bonus=_dt_gen_bonus,
            event_converter_bonus=_dt_conv_bonus,
        )
        for k, v in changes.items():
            if k == "market_gold":
                market_gold += int(v)
            elif k == "war_camp_stamina":
                war_camp_stamina = min(10, war_camp_stamina + int(float(v)))
            elif k == "companion_cookie":
                companion_cookie += int(v)
            else:
                total_changes[k] = total_changes.get(k, 0) + v
                # Mirror converter deductions into raw_inv so later buildings see updated stock
                if b_def["type"] == "converter" and v < 0:
                    raw_inv[k] = raw_inv.get(k, 0) + v  # v is negative

    # Apply market gold bonus/penalty after production.
    if market_gold > 0 and _dt_market_gold_bonus:
        market_gold = max(0, int(market_gold * (1 + _dt_market_gold_bonus)))

    return total_changes, market_gold, war_camp_stamina, companion_cookie


async def _complete_project(
    bot, user_id: str, server_id: str, proj: dict, event_effects: dict | None = None
) -> dict:
    """Apply the effects of a completed project. Returns a label dict."""
    ptype = proj["project_type"]
    data = proj.get("data", {})
    _ev = event_effects or {}

    if ptype == "construction":
        building_type = data.get("building_type")
        plot_index = data.get("plot_index")
        is_meta = data.get("is_meta", False)
        if building_type and plot_index:
            await bot.database.settlement.build_structure(
                user_id, server_id, building_type, plot_index, is_meta
            )
        return {
            "label": f"{building_type.replace('_', ' ').title()}",
            "is_meta": is_meta,
        }

    elif ptype == "upgrade":
        building_id = proj.get("target_id")
        building_type = data.get("building_type", "building")
        if building_id:
            await bot.database.settlement.upgrade_building_tier(building_id)
            if building_type == "town_hall":
                await bot.database.settlement.expand_building_slots(user_id, server_id)
        return {"label": f"Upgraded {building_type.replace('_', ' ').title()}"}

    elif ptype == "research":
        building_type = data.get("building_type", "")
        if building_type:
            await bot.database.settlement.complete_research(
                user_id, server_id, building_type
            )
        return {"label": f"{building_type.replace('_', ' ').title()} research - "}

    elif ptype == "plot_develop":
        plot_index = data.get("plot_index")
        bonus_type = data.get("bonus_type")
        if plot_index is not None and bonus_type:
            await bot.database.plots.develop_plot(
                user_id, server_id, plot_index, bonus_type
            )
            plots = await bot.database.plots.get_plots(user_id, server_id)
            developed_count = sum(1 for p in plots if p["is_developed"])
            await hof_triggers.check_king(bot, user_id, developed_count)
        return {"label": f"Plot {plot_index} Excavated"}

    elif ptype == "foundry_idlem":
        base_idlem = data.get("idlem_per_turn", IDLEM_PER_TURN_BASE) * _ev.get(
            "idlem_mult", 1.0
        )
        # Design: 1-2 Idlem per turn with variance
        idlem = int(base_idlem) + random.randint(0, 1)
        await bot.database.settlement.add_idlem(user_id, server_id, idlem)
        return {"label": "Foundry produced Idlem", "idlem": idlem}

    elif ptype == "uber_statue":
        statue_type = data.get("statue_type")
        slot_index = data.get("slot_index", 0)
        if statue_type:
            await bot.database.settlement.unlock_statue(
                user_id, server_id, statue_type, slot_index
            )
        label = f"{statue_type.title()} Statue" if statue_type else "Statue"
        return {"label": f"{label} Built"}

    elif ptype == "statue_upgrade":
        statue_type = data.get("statue_type")
        target_tier = data.get("target_tier", 2)
        if statue_type:
            await bot.database.settlement.upgrade_statue_tier(
                user_id, server_id, statue_type
            )
        label = f"{statue_type.title()} Statue" if statue_type else "Statue"
        return {"label": f"{label} Upgraded to T{target_tier}"}

    elif ptype == "town_hall_upgrade":
        await bot.database.settlement.upgrade_town_hall(user_id, server_id)
        return {"label": "Town Hall Upgraded"}

    return {"label": ptype}


def _resolve_band(effect_val, ev_data: dict):
    """Resolves a banded effect value: 'band' → ev_data['band'], 'neg_band' → -ev_data['band'], else passthrough."""
    if effect_val == "band":
        return ev_data.get("band", 0)
    if effect_val == "neg_band":
        return -ev_data.get("band", 0)
    return effect_val


async def _apply_event_effects(
    bot, user_id: str, server_id: str, ev_def: dict, ev_data: dict | None = None
) -> dict:
    """Applies on-fire/on-fail effects for a settlement event. Returns extra context (e.g. plague losses)."""
    import math

    effects = ev_def.get("effects", {})
    ev_data = ev_data or {}
    result: dict = {}

    if "grant_zeal" in effects:
        val = int(_resolve_band(effects["grant_zeal"], ev_data))
        if val < 0:
            zeal_data = await bot.database.settlement.get_zeal_data(user_id, server_id)
            val = -min(-val, zeal_data.get("settlement_zeal", 0))
        await bot.database.settlement.add_zeal(user_id, server_id, val)
        result["zeal_granted"] = val

    if "grant_blueprints" in effects:
        val = _resolve_band(effects["grant_blueprints"], ev_data)
        await bot.database.settlement_materials.modify(
            user_id, "unidentified_blueprint", int(val)
        )

    if "on_fail_disable" in effects:
        # Crisis event warning expired without player intervention — disable target building.
        target_type = ev_data.get("target_building")
        if target_type:
            building = await bot.database.settlement.get_building_by_type(
                user_id, server_id, target_type
            )
            if building and not building.is_disabled:
                await bot.database.settlement.disable_building(building.id)

    if "on_fail_lose_workers_pct" in effects:
        # Plague Outbreak: remove a percentage of workers from every building.
        pct = _resolve_band(effects["on_fail_lose_workers_pct"], ev_data)
        settlement = await bot.database.settlement.get_settlement(user_id, server_id)
        losses = []
        for b in settlement.buildings if settlement else []:
            if b.workers_assigned <= 0:
                continue
            lost = max(1, math.ceil(b.workers_assigned * pct))
            new_count = max(0, b.workers_assigned - lost)
            await bot.database.settlement.assign_workers(b.id, new_count)
            losses.append({"name": b.name, "lost": lost})
        result["plague_losses"] = losses

    return result


_COMBAT_EVENTS: frozenset[str] = frozenset(
    {"bandit_raid", "plague_outbreak", "void_incursion", "fire_hazard"}
)


async def _check_schedule_events(
    bot, user_id: str, server_id: str, total_turns: int
) -> None:
    """Schedules upcoming events that are due based on total turns."""
    existing = await bot.database.settlement.get_active_events(user_id, server_id)
    existing_keys = {ev["event_key"] for ev in existing}
    combat_event_active = bool(existing_keys & _COMBAT_EVENTS)

    # Fetch the player's buildings so we can enforce requirements and pick targets.
    settlement = await bot.database.settlement.get_settlement(user_id, server_id)
    player_building_types: set[str] = set()
    if settlement and settlement.buildings:
        player_building_types = {
            b.building_type for b in settlement.buildings if not b.is_meta
        }

    # First pass: figure out which events are due this turn, without firing any yet.
    # This lets combat events be rolled as one group below instead of each being
    # checked (and potentially fired) independently in the same tick.
    eligible: list[tuple[str, dict]] = []
    for key, ev_def in SETTLEMENT_EVENTS.items():
        if key in existing_keys:
            continue  # Already active

        trigger_at = ev_def.get("trigger_at", [])
        rec_interval = ev_def.get("recurring_interval", 0)

        should_trigger = False
        if total_turns in trigger_at:
            should_trigger = True
        elif rec_interval > 0 and total_turns > 0:
            last_trigger = max((t for t in trigger_at if t <= total_turns), default=0)
            if last_trigger > 0:
                turns_since = total_turns - last_trigger
                if turns_since > 0 and turns_since % rec_interval == 0:
                    should_trigger = True

        if not should_trigger:
            continue

        chance = ev_def.get("trigger_chance", 1.0)
        if chance < 1.0 and random.random() >= chance:
            continue  # Missed the roll — re-checked at the next recurring_interval.

        # Check building requirements (at least one must be present).
        requires = ev_def.get("requires_buildings", [])
        if requires and not any(b in player_building_types for b in requires):
            continue

        eligible.append((key, ev_def))

    # Combat events: roll once across all due combat events and fire at most one,
    # and only if no combat event is already active/pending.
    combat_due = [item for item in eligible if item[0] in _COMBAT_EVENTS]
    non_combat_due = [item for item in eligible if item[0] not in _COMBAT_EVENTS]

    to_fire = list(non_combat_due)
    if combat_due and not combat_event_active:
        to_fire.append(random.choice(combat_due))

    for key, ev_def in to_fire:
        # Roll banded modifier.
        ev_data: dict = {}
        bands = ev_def.get("modifier_bands", [])
        if bands:
            band_val = random.choice(bands)
            ev_data["band"] = band_val
            # Store as integer percentage for display substitution.
            if isinstance(band_val, float) and band_val < 5:
                ev_data["band_pct"] = round(band_val * 100)
            else:
                ev_data["band_pct"] = int(band_val)

        # Roll duration.
        dur_bands = ev_def.get("duration_bands", [])
        if dur_bands:
            ev_data["duration"] = random.choice(dur_bands)
        elif "duration_turns" in ev_def:
            ev_data["duration"] = ev_def["duration_turns"]

        # Determine crisis target building.
        targets_any = ev_def.get("targets_any_building", False)
        targets_types = ev_def.get("targets_building_types", [])
        if targets_any and player_building_types:
            target = random.choice(sorted(player_building_types))
            ev_data["target_building"] = target
            ev_data["target_building_label"] = target.replace("_", " ").title()
        elif targets_types:
            available = [t for t in targets_types if t in player_building_types]
            if available:
                target = random.choice(available)
                ev_data["target_building"] = target
                ev_data["target_building_label"] = target.replace("_", " ").title()
            else:
                continue  # Crisis can't fire without a valid target.

        etype = ev_def.get("type", "instant")
        warning = ev_def.get("advance_warning_turns", 0)
        duration = ev_data.get("duration", ev_def.get("duration_turns", 3))
        data_arg = ev_data if ev_data else None

        if etype == "upcoming" and warning > 0:
            await bot.database.settlement.add_event(
                user_id,
                server_id,
                key,
                "upcoming",
                turns_until=warning,
                turns_remaining=0,
                data=data_arg,
            )
        elif etype == "ongoing":
            await bot.database.settlement.add_event(
                user_id,
                server_id,
                key,
                "ongoing",
                turns_until=0,
                turns_remaining=duration,
                data=data_arg,
            )
        elif etype == "instant":
            await _apply_event_effects(bot, user_id, server_id, ev_def, ev_data)


# ---------------------------------------------------------------------------
# Black Market — value calculation + processing turns
# ---------------------------------------------------------------------------


def resolve_bm_event_value_bonus(active_events: list) -> float:
    """Sums the `bm_value_bonus` effect (e.g. Merchant Caravan) across active ongoing events."""
    bonus = 0.0
    for ev in active_events:
        if ev["event_type"] != "ongoing":
            continue
        ev_def = SETTLEMENT_EVENTS.get(ev["event_key"], {})
        raw_val = ev_def.get("effects", {}).get("bm_value_bonus", 0.0)
        ev_data = ev.get("data") or {}
        if raw_val == "band":
            raw_val = ev_data.get("band", 0.0)
        elif raw_val == "neg_band":
            raw_val = -ev_data.get("band", 0.0)
        if isinstance(raw_val, (int, float)):
            bonus += raw_val
    return bonus


def calculate_offer_value(
    offer: dict,
    tree_nodes: dict[str, int],
    bm_tier: int = 1,
) -> int:
    """
    Computes the total Value score for a Black Market offer.
    tree_nodes: {node_key: level} from bm_passive_tree.
    bm_tier: current Black Market building tier (1–5).
    """
    raw_value = sum(
        qty * BM_ITEM_VALUES.get(resource, 0)
        for resource, qty in offer.items()
        if qty > 0
    )

    # Value multiplier from BM tree (value branch)
    value_mult = 1.0
    for key in ("value_1", "value_2", "value_3"):
        if key in tree_nodes:
            bonuses = [0.05, 0.10, 0.15]
            idx = int(key.split("_")[-1]) - 1
            value_mult += bonuses[min(idx, len(bonuses) - 1)]

    return max(0, int(raw_value * value_mult))


def compute_processing_turns(
    value: int,
    bm_tier: int,
    tree_nodes: dict[str, int],
) -> int:
    """Returns the number of Development Turns required to process a deal.

    Turns stay at BM_TURNS_MIN below BM_TURNS_SCALE_START value, then rise
    along a saturating curve that approaches BM_TURNS_MAX as value grows —
    so even extreme offers (billions in value) top out near the cap instead
    of scaling linearly forever.
    """
    excess = max(0.0, value - BM_TURNS_SCALE_START)
    turn_range = BM_TURNS_MAX - BM_TURNS_MIN
    raw = BM_TURNS_MIN + turn_range * excess / (excess + BM_TURNS_HALF_SATURATION)

    # Tier reduction (T5 = −30%)
    tier_reduction = (bm_tier - 1) * 0.075  # 0% T1 → 30% T5
    raw *= max(0.0, 1.0 - tier_reduction)

    # Efficiency tree node: levels don't stack — only the current level's
    # reduction applies.
    eff_level = tree_nodes.get("efficiency", 0)
    if eff_level > 0:
        reductions = BM_TREE_NODES["efficiency"]["reductions"]
        raw *= 1.0 - reductions[min(eff_level, len(reductions)) - 1]

    turns = max(1, int(raw))

    # Instant deals node: if ≤ 5 turns, complete immediately
    if "instant_deals" in tree_nodes and turns <= 5:
        turns = 0

    return turns


# ---------------------------------------------------------------------------
# Black Market — reward rolling
# ---------------------------------------------------------------------------


_GEAR_SLOTS = ["weapon", "armor", "accessory", "glove", "boot", "helmet"]
_GEAR_SLOT_WEIGHTS = [35, 10, 25, 10, 10, 10]
_GEAR_SLOT_LABELS = {
    "weapon": "Weapon",
    "armor": "Armor",
    "accessory": "Accessory",
    "glove": "Gloves",
    "boot": "Boots",
    "helmet": "Helmet",
}

_CURRENCY_LABELS = {
    "refinement_runes": "Rune of Refinement",
    "potential_runes": "Rune of Potential",
    "shatter_runes": "Rune of Shattering",
    "imbue_runes": "Rune of Imbuing",
    "dragon_key": "Dragon Key",
    "angel_key": "Angel Key",
    "soul_cores": "Soul Core",
    "balance_fragment": "Fragment of Balance",
    "void_frags": "Void Fragment",
    "magma_core": "Magma Core",
    "life_root": "Life Root",
    "spirit_shard": "Spirit Shard",
    "cosmic_dust": "Cosmic Dust",
    "antique_tome": "Antique Tome",
    "pinnacle_key": "Pinnacle Key",
    "spirit_stones": "Spirit Stone",
    "diviners_rod": "Diviner's Rod",
    "unidentified_blueprint": "Unidentified Blueprint",
    "guild_ticket": "Guild Ticket",
    "curios": "Curio",
    "idea_ore": "Idea Ore",
    "idea_logs": "Idea Logs",
    "magic_logs": "Magic Logs",
    "reinforced_bones": "Reinforced Bones",
    "titanium_bones": "Titanium Bones",
    "partnership_runes": "Partnership Rune",
    "mirage_runes_imperfect": "Mirage Rune (Imperfect)",
    "mirage_runes_perfected": "Mirage Rune (Perfected)",
    "paradise_jewels": "Paradise Jewel",
}


def roll_bm_rewards(
    value: int,
    active_biases: list[str],
    player_level: int = 1,
    tree_nodes: dict | None = None,
    bm_logger=None,
) -> dict:
    """
    Rolls Black Market rewards for a completed deal.

    Returns a dict:
      {
        "gold": int,
        "currencies": {currency_key: qty},
        "items": [{"type": "weapon"|"armor"|etc., "level": int}],
        "summary_lines": [str],  # one human-readable entry per reward type
      }
    """
    base_rolls = max(1, math.floor(value / BM_ROLLS_PER_VALUE))

    result: dict = {
        "gold": 0,
        "currencies": {},
        "items": [],
        "summary_lines": [],
    }

    categories = [c for c, _ in BM_BASE_LOOT_WEIGHTS]
    weights = [w for _, w in BM_BASE_LOOT_WEIGHTS]

    # Extra rolls from bias tree nodes — use the player's ACTUAL invested level
    _nodes = tree_nodes or {}
    extra_rolls: list[str] = []
    for bias_key in active_biases:
        node = BM_TREE_NODES.get(bias_key)
        if not node or node.get("branch") != "bias":
            continue
        invested_level = _nodes.get(bias_key, 0)
        if invested_level <= 0:
            continue  # not actually unlocked
        rolls_list = node.get("extra_rolls", [1])
        extra_count = rolls_list[min(invested_level - 1, len(rolls_list) - 1)]
        category = node.get("category", "rune")
        extra_rolls.extend([category] * extra_count)

    # Fortune's Cut — always-on Idlem sink: 1% chance per level of one bonus
    # random-category roll. Not part of active_biases (no per-deal toggle).
    fortune_lvl = _nodes.get("fortune_bias", 0)
    if fortune_lvl > 0 and random.random() < fortune_lvl * 0.01:
        extra_rolls.append(random.choices(categories, weights=weights, k=1)[0])

    if bm_logger:
        bm_logger.log_roll_plan(base_rolls, extra_rolls)

    # Variety tracker: track which sub-types have been used per category this deal.
    # Once all sub-types in a pool are used, allow repeats.
    _used: dict[str, list[str]] = {
        "essence": [],
        "rune": [],
        "gathering": [],
        "boss_key": [],
    }

    def _pick_varied(pool: list, used_list: list) -> str:
        """Pick from pool, preferring sub-types not yet used this deal."""
        fresh = [x for x in pool if x not in used_list]
        chosen = random.choice(fresh if fresh else pool)
        used_list.append(chosen)
        return chosen

    _roll_num = [0]

    def _roll_category(cat: str) -> None:
        _roll_num[0] += 1
        n = _roll_num[0]

        if cat == "gold":
            g = random.randint(BM_GOLD_MIN, BM_GOLD_MAX)
            result["gold"] += g
            if bm_logger:
                bm_logger.log_roll(n, cat, "gold", g)

        elif cat == "rune":
            rune_pool = [
                "refinement_runes",
                "potential_runes",
                "shatter_runes",
                "imbue_runes",
                "partnership_runes",
            ]
            chosen = _pick_varied(rune_pool, _used["rune"])
            qty = (
                random.randint(1, 3)
                if chosen not in ("imbue_runes", "partnership_runes")
                else 1
            )
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + qty
            if bm_logger:
                bm_logger.log_roll(n, cat, chosen, qty)

        elif cat == "boss_key":
            key_pool = [
                "soul_cores",
                "void_frags",
                "balance_fragment",
                "dragon_key",
                "angel_key",
            ]
            key_weights = [5, 3, 1, 1, 1]
            chosen = random.choices(key_pool, weights=key_weights, k=1)[0]
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + 1
            if bm_logger:
                bm_logger.log_roll(n, cat, chosen, 1)

        elif cat == "gathering":
            # T1–T5 materials per skill; qty_base scaled for meaningful quantities
            mat_pool = [
                # Mining (T1–T5)
                ("iron_ore", 1000),
                ("coal_ore", 800),
                ("gold_ore", 600),
                ("platinum_ore", 400),
                ("idea_ore", 200),
                # Woodcutting (T1–T5)
                ("oak_logs", 1000),
                ("willow_logs", 800),
                ("mahogany_logs", 600),
                ("magic_logs", 400),
                ("idea_logs", 200),
                # Fishing (T1–T5)
                ("desiccated_bones", 1000),
                ("regular_bones", 800),
                ("sturdy_bones", 600),
                ("reinforced_bones", 400),
                ("titanium_bones", 200),
            ]
            mat_names = [m for m, _ in mat_pool]
            fresh = [m for m in mat_names if m not in _used["gathering"]]
            if fresh:
                chosen = random.choice(fresh)
                qty_base = next(q for m, q in mat_pool if m == chosen)
            else:
                chosen, qty_base = random.choice(mat_pool)
            _used["gathering"].append(chosen)
            qty = random.randint(qty_base // 2, qty_base)
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + qty
            if bm_logger:
                bm_logger.log_roll(n, cat, chosen, qty)

        elif cat == "essence":
            from core.combat.economy.drops import roll_essence_drop

            chosen_ess = roll_essence_drop()
            qty = random.randint(1, 3)
            result["currencies"][f"essence_{chosen_ess}"] = (
                result["currencies"].get(f"essence_{chosen_ess}", 0) + qty
            )
            if bm_logger:
                bm_logger.log_roll(n, cat, f"essence_{chosen_ess}", qty)

        elif cat == "gear":
            slot = random.choices(_GEAR_SLOTS, weights=_GEAR_SLOT_WEIGHTS, k=1)[0]
            result["items"].append({"type": slot, "level": min(player_level, 100)})
            if bm_logger:
                bm_logger.log_roll(n, cat, slot, 1)

        elif cat == "settler_mat":
            mat_pool = ["magma_core", "life_root", "spirit_shard", "cosmic_dust"]
            chosen = random.choice(mat_pool)
            qty = (
                random.randint(40, 60)
                if chosen == "cosmic_dust"
                else random.randint(1, 2)
            )
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + qty
            if bm_logger:
                bm_logger.log_roll(n, cat, chosen, qty)

        elif cat == "curio":
            result["currencies"]["curios"] = result["currencies"].get("curios", 0) + 1
            if bm_logger:
                bm_logger.log_roll(n, cat, "curio", 1)

        elif cat == "high_end":
            pool = [
                "antique_tome",
                "pinnacle_key",
                "spirit_stones",
                "diviners_rod",
                "unidentified_blueprint",
            ]
            chosen = random.choice(pool)
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + 1
            if bm_logger:
                bm_logger.log_roll(n, cat, chosen, 1)

        elif cat == "guild_ticket":
            qty = random.randint(1, 3)
            result["currencies"]["guild_ticket"] = (
                result["currencies"].get("guild_ticket", 0) + qty
            )
            if bm_logger:
                bm_logger.log_roll(n, cat, "guild_ticket", qty)

    # Premier tier — extremely rare table, ~100× less likely than a gold roll per spin
    # Gold: weight 25 / total ~95 → premier chance = 25 / (95 * 100)
    _PREMIER_CHANCE = 25 / (95 * 100)
    _PREMIER_POOL = [
        "mirage_runes_imperfect",
        "paradise_jewels",
        "mirage_runes_perfected",
    ]
    _PREMIER_WEIGHTS = [100, 2500, 1]

    def _try_premier(roll_n: int) -> bool:
        """Returns True if a premier item was awarded instead of the normal roll."""
        if random.random() >= _PREMIER_CHANCE:
            return False
        chosen = random.choices(_PREMIER_POOL, weights=_PREMIER_WEIGHTS, k=1)[0]
        result["currencies"][chosen] = result["currencies"].get(chosen, 0) + 1
        if bm_logger:
            bm_logger.log_roll(roll_n, "premier", chosen, 1)
        return True

    # Base rolls
    for _ in range(base_rolls):
        _roll_num[0] += 1
        if not _try_premier(_roll_num[0]):
            _roll_num[0] -= 1  # reuse the number for the normal roll
            cat = random.choices(categories, weights=weights, k=1)[0]
            _roll_category(cat)

    # Extra bias rolls
    for cat in extra_rolls:
        _roll_num[0] += 1
        if not _try_premier(_roll_num[0]):
            _roll_num[0] -= 1
            _roll_category(cat)

    # Build compact summary — one segment per reward type, joined for single-line display
    parts: list[str] = []
    if result["gold"] > 0:
        parts.append(f"{GOLD_COIN} {result['gold']:,}g")
    for cur, qty in result["currencies"].items():
        if cur.startswith("essence_"):
            ess = cur[len("essence_") :].replace("_", " ").title()
            label = f"Essence of {ess}"
        else:
            label = _CURRENCY_LABELS.get(cur) or cur.replace("_", " ").title()
        parts.append(f"{qty}× {label}")
    if result["items"]:
        from collections import Counter

        slot_counts = Counter(item["type"] for item in result["items"])
        gear_parts = [
            f"{cnt}× {_GEAR_SLOT_LABELS.get(slot, slot.title())}"
            for slot, cnt in slot_counts.items()
        ]
        parts.append(f"⚔️ {', '.join(gear_parts)}")

    # One reward type per entry — callers join/slice as needed so a single
    # extreme-value deal (thousands of currency units) can't produce one
    # unbounded mega-string that blows past Discord's 1024-char field cap.
    result["summary_lines"] = parts

    if bm_logger:
        bm_logger.log_summary(result)

    return result


_SETTLEMENT_MATERIAL_COLS: frozenset[str] = frozenset(
    [
        "magma_core",
        "life_root",
        "spirit_shard",
        "celestial_stone",
        "infernal_cinder",
        "void_crystal",
        "bound_crystal",
        "diviners_rod",
        "unidentified_blueprint",
    ]
)

_GATHERING_SKILL_MAP: dict[str, str] = {
    "iron_ore": "mining",
    "coal_ore": "mining",
    "gold_ore": "mining",
    "platinum_ore": "mining",
    "idea_ore": "mining",
    "oak_logs": "woodcutting",
    "willow_logs": "woodcutting",
    "mahogany_logs": "woodcutting",
    "magic_logs": "woodcutting",
    "idea_logs": "woodcutting",
    "desiccated_bones": "fishing",
    "regular_bones": "fishing",
    "sturdy_bones": "fishing",
    "reinforced_bones": "fishing",
    "titanium_bones": "fishing",
}


async def _grant_bm_rewards(bot, user_id: str, server_id: str, rewards: dict) -> None:
    """Applies a rolled BM reward dict to the player."""
    if rewards.get("gold", 0) > 0:
        await bot.database.users.modify_gold(user_id, rewards["gold"])

    for cur, qty in rewards.get("currencies", {}).items():
        if cur.startswith("essence_"):
            ess_type = cur[len("essence_") :]
            for _ in range(qty):
                await bot.database.essences.add(user_id, ess_type)
        elif cur in ("guild_ticket",):
            await bot.database.partners.add_tickets(user_id, qty)
        elif cur == "cosmic_dust":
            await bot.database.alchemy.modify_cosmic_dust(user_id, qty)
        elif cur in _GATHERING_SKILL_MAP:
            skill = _GATHERING_SKILL_MAP[cur]
            try:
                await bot.database.skills.update_single_resource(
                    user_id, server_id, skill, cur, qty
                )
            except Exception:
                pass
        elif cur in _SETTLEMENT_MATERIAL_COLS:
            try:
                await bot.database.settlement_materials.modify(user_id, cur, qty)
            except Exception:
                pass
        elif cur == "paradise_jewels":
            try:
                await bot.database.uber.increment_paradise_jewels(
                    user_id, server_id, qty
                )
            except Exception:
                pass
        else:
            try:
                await bot.database.users.modify_currency(user_id, cur, qty)
            except Exception:
                pass

    for item_spec in rewards.get("items", []):
        try:
            from core.combat.economy.loot import (
                generate_accessory,
                generate_armor,
                generate_boot,
                generate_glove,
                generate_helmet,
                generate_weapon,
            )

            slot = item_spec.get("type", "random")
            if slot == "random":
                slot = random.choices(_GEAR_SLOTS, weights=_GEAR_SLOT_WEIGHTS, k=1)[0]
            ilvl = item_spec.get("level", 1)
            if slot == "weapon":
                item = await generate_weapon(user_id, ilvl)
                await bot.database.equipment.create_weapon(item)
            elif slot == "armor":
                item = await generate_armor(user_id, ilvl)
                await bot.database.equipment.create_armor(item)
            elif slot == "accessory":
                item = await generate_accessory(user_id, ilvl)
                await bot.database.equipment.create_accessory(item)
            elif slot == "glove":
                item = await generate_glove(user_id, ilvl)
                await bot.database.equipment.create_glove(item)
            elif slot == "boot":
                item = await generate_boot(user_id, ilvl)
                await bot.database.equipment.create_boot(item)
            elif slot == "helmet":
                item = await generate_helmet(user_id, ilvl)
                await bot.database.equipment.create_helmet(item)
        except Exception:
            pass


async def complete_bm_deal_instant(
    bot,
    user_id: str,
    server_id: str,
    value: int,
    active_biases: list[str],
    player_level: int,
    tree_nodes: dict,
) -> dict:
    """Process a 0-turn BM deal immediately without storing in DB."""
    from core.settlement.bm_log import BMLogger

    bm_log = BMLogger(user_id, value, 0)
    bm_log.log_tree(tree_nodes, active_biases)
    rewards = roll_bm_rewards(
        value, active_biases, player_level, tree_nodes=tree_nodes, bm_logger=bm_log
    )
    bm_log.close()
    async with bot.database.transaction():
        await _grant_bm_rewards(bot, user_id, server_id, rewards)
    return rewards
