"""
core/settlement/turn_engine.py
Pure functions for the Settlement Turns Economy:
  - Zeal earning / daily-cap logic
  - Development Turn conversion
  - Next Turn processing (projects, deals, passive zeal, events)
  - Black Market value calculation, turn cost, reward rolling
  - Event checking and trigger logic
"""
from __future__ import annotations

import math
import random
from typing import TYPE_CHECKING

from core.settlement.constants import (
    BM_BASE_LOOT_WEIGHTS,
    BM_GOLD_MAX,
    BM_GOLD_MIN,
    BM_ITEM_VALUES,
    BM_ROLLS_PER_VALUE,
    BM_TREE_NODES,
    BM_TURNS_BASE,
    BM_TURNS_PER_VALUE,
    IDLEM_PER_TURN_BASE,
    PASSIVE_ZEAL_PER_HOUR_BASE,
    PROJECT_CONSTRUCTION_DT,
    PROJECT_UPGRADE_DT_PER_TIER,
    SETTLEMENT_EVENTS,
    WORKERS_PER_TURN_BASE,
    ZEAL_DAILY_HARD_CAP,
    ZEAL_DAILY_SOFT_CAP,
    ZEAL_PER_COMBAT,
    ZEAL_TO_DT,
)

if TYPE_CHECKING:
    pass


# ---------------------------------------------------------------------------
# Zeal economy
# ---------------------------------------------------------------------------

def compute_zeal_gain(base: int, earned_today: int) -> int:
    """
    Returns the actual Zeal that should be credited, applying the soft/hard cap.

    - Below ZEAL_DAILY_SOFT_CAP: full amount.
    - Between soft and hard cap: halved.
    - Above ZEAL_DAILY_HARD_CAP: nothing.
    """
    if earned_today >= ZEAL_DAILY_HARD_CAP:
        return 0
    remaining_to_hard = ZEAL_DAILY_HARD_CAP - earned_today
    remaining_to_soft = max(0, ZEAL_DAILY_SOFT_CAP - earned_today)

    full_portion = min(base, remaining_to_soft)
    halved_portion = min(base - full_portion, remaining_to_hard - full_portion)

    return full_portion + (halved_portion // 2)


def zeal_to_dt(zeal: int) -> tuple[int, int]:
    """Returns (development_turns, leftover_zeal)."""
    turns = zeal // ZEAL_TO_DT
    leftover = zeal % ZEAL_TO_DT
    return turns, leftover


def passive_zeal_for_period(hours: float, town_hall_tier: int) -> int:
    """Passive Zeal generated by the settlement over a given number of hours."""
    rate = PASSIVE_ZEAL_PER_HOUR_BASE * (1 + (town_hall_tier - 1) * 0.10)
    return int(hours * rate)


# ---------------------------------------------------------------------------
# Project DT costs
# ---------------------------------------------------------------------------

def construction_dt_cost(building_type: str, event_effects: dict | None = None) -> int:
    base = PROJECT_CONSTRUCTION_DT.get(building_type, 12)
    if event_effects and event_effects.get("construction_dt_halved"):
        base = max(1, base // 2)
    return base


def upgrade_dt_cost(building_type: str, target_tier: int) -> int:
    per_tier = PROJECT_UPGRADE_DT_PER_TIER.get(
        building_type, PROJECT_UPGRADE_DT_PER_TIER["default"]
    )
    return per_tier * target_tier


# ---------------------------------------------------------------------------
# Next Turn processor
# ---------------------------------------------------------------------------

async def process_next_turn(
    bot,
    user_id: str,
    server_id: str,
    town_hall_tier: int,
) -> dict:
    """
    Processes one Development Turn. Returns a summary dict with keys:
      - turns_gained: int
      - zeal_spent: int
      - projects_completed: list[dict]
      - deal_completed: dict | None  (the deal if it finished this turn)
      - deal_rewards: dict | None    (granted rewards if deal completed)
      - events_fired: list[str]      (event names that fired)
      - events_expired: list[str]
      - passive_zeal_added: int
      - workers_from_nursery: int
      - idlem_from_foundry: int
    """
    summary: dict = {
        "turns_gained": 1,
        "zeal_spent": ZEAL_TO_DT,
        "projects_completed": [],
        "deal_completed": None,
        "deal_rewards": None,
        "events_fired": [],
        "events_expired": [],
        "passive_zeal_added": 0,
        "workers_from_nursery": 0,
        "idlem_from_foundry": 0,
    }

    # 1. Read active ongoing events BEFORE advancing projects so their multipliers
    #    apply to any projects that complete this turn.
    active_events = await bot.database.settlement.get_active_events(user_id, server_id)
    event_effects: dict = {}
    for _ev in active_events:
        _ev_def = SETTLEMENT_EVENTS.get(_ev.get("event_key", ""), {})
        for _k, _v in _ev_def.get("effects", {}).items():
            if _k not in event_effects:
                event_effects[_k] = _v  # first-defined wins; only one of each type expected

    # 2. Advance all projects; collect completed ones
    completed = await bot.database.settlement.advance_projects(user_id, server_id)
    for proj in completed:
        result = await _complete_project(bot, user_id, server_id, proj, event_effects)
        await bot.database.settlement.delete_project(proj["id"])
        summary["projects_completed"].append({
            "type": proj["project_type"],
            "label": result.get("label", proj["project_type"]),
        })
        if proj["project_type"] == "nursery":
            summary["workers_from_nursery"] += result.get("workers", 0)
        elif proj["project_type"] == "foundry_idlem":
            summary["idlem_from_foundry"] += result.get("idlem", 0)

    # 3. Advance pending Black Market deal
    deal = await bot.database.settlement.get_pending_deal(user_id, server_id)
    if deal:
        deal = await bot.database.settlement.decrement_deal_turn(user_id, server_id)
        if deal and deal["turns_remaining"] <= 0:
            # Deal complete — roll rewards
            user_row = await bot.database.users.get(user_id, server_id)
            player_level = user_row["level"] if user_row else 1
            deal_tree_nodes = await bot.database.settlement.get_bm_tree(user_id, server_id)
            rewards = roll_bm_rewards(
                deal["total_value"], deal["active_biases"], player_level,
                tree_nodes=deal_tree_nodes,
            )
            await _grant_bm_rewards(bot, user_id, server_id, rewards)
            await bot.database.settlement.delete_pending_deal(user_id, server_id)
            summary["deal_completed"] = deal
            summary["deal_rewards"] = rewards

    # 4. Tick events
    newly_fired, expired = await bot.database.settlement.tick_events(user_id, server_id)
    for ev in expired:
        await bot.database.settlement.remove_event(ev["id"])
        summary["events_expired"].append(SETTLEMENT_EVENTS.get(ev["event_key"], {}).get("name", ev["event_key"]))

    for ev in newly_fired:
        ev_def = SETTLEMENT_EVENTS.get(ev["event_key"], {})
        await _apply_event_effects(bot, user_id, server_id, ev_def)
        # Convert upcoming → ongoing if it has duration
        dur = ev_def.get("duration_turns", 0)
        if dur > 0:
            await bot.database.settlement.add_event(
                user_id, server_id, ev["event_key"], "ongoing",
                turns_until=0, turns_remaining=dur,
            )
        await bot.database.settlement.remove_event(ev["id"])
        summary["events_fired"].append(ev_def.get("name", ev["event_key"]))

    # 5. Increment total turns
    await bot.database.settlement.increment_turns(user_id, server_id)
    turns_data = await bot.database.settlement.get_turns_data(user_id, server_id)
    new_total = turns_data["total_development_turns"]

    # 6. Check for new events to schedule
    await _check_schedule_events(bot, user_id, server_id, new_total)

    # 7. Passive Zeal generation per turn (~10 base, +10% per TH tier above 1)
    passive_zeal = max(1, int(PASSIVE_ZEAL_PER_HOUR_BASE * (1 + (town_hall_tier - 1) * 0.10)))
    await bot.database.settlement.add_pending_zeal(user_id, server_id, passive_zeal)
    summary["passive_zeal_added"] = passive_zeal

    return summary


async def _complete_project(
    bot, user_id: str, server_id: str, proj: dict, event_effects: dict | None = None
) -> dict:
    """Apply the effects of a completed project. Returns a label dict."""
    ptype = proj["project_type"]
    data = proj.get("data", {})
    _ev = event_effects or {}

    if ptype == "construction":
        building_type = data.get("building_type")
        plot_index = data.get("plot_index")
        is_meta = data.get("is_meta", False)
        if building_type and plot_index:
            await bot.database.settlement.build_structure(
                user_id, server_id, building_type, plot_index, is_meta
            )
        return {"label": f"Built {building_type.replace('_', ' ').title()}"}

    elif ptype == "upgrade":
        building_id = proj.get("target_id")
        if building_id:
            await bot.database.settlement.upgrade_building_tier(building_id)
        label = data.get("building_type", "building")
        return {"label": f"Upgraded {label.replace('_', ' ').title()}"}

    elif ptype == "research":
        building_type = data.get("building_type", "")
        if building_type:
            await bot.database.settlement.complete_research(user_id, server_id, building_type)
        return {"label": f"Researched {building_type.replace('_', ' ').title()}"}

    elif ptype == "nursery":
        workers = int(data.get("workers_per_turn", WORKERS_PER_TURN_BASE)
                      * _ev.get("nursery_mult", 1.0))
        # Worker production increments ideology follower count
        try:
            user_row = await bot.database.users.get(user_id, server_id)
            if user_row:
                ideology_name = user_row["ideology"] if isinstance(user_row, dict) else user_row[8]
                current = await bot.database.social.get_follower_count(ideology_name)
                await bot.database.social.update_followers(ideology_name, current + workers)
        except Exception:
            pass
        return {"label": "Nursery produced workers", "workers": workers}

    elif ptype == "foundry_idlem":
        base_idlem = data.get("idlem_per_turn", IDLEM_PER_TURN_BASE) * _ev.get("idlem_mult", 1.0)
        # Design: 1-2 Idlem per turn with variance
        idlem = int(base_idlem) + random.randint(0, 1)
        await bot.database.settlement.add_idlem(user_id, idlem)
        return {"label": "Foundry produced Idlem", "idlem": idlem}

    return {"label": ptype}


async def _apply_event_effects(bot, user_id: str, server_id: str, ev_def: dict) -> None:
    effects = ev_def.get("effects", {})

    if "grant_zeal" in effects:
        await bot.database.settlement.add_zeal(user_id, effects["grant_zeal"])

    if "grant_blueprints" in effects:
        await bot.database.users.modify_currency(user_id, "unidentified_blueprint", effects["grant_blueprints"])


async def _check_schedule_events(bot, user_id: str, server_id: str, total_turns: int) -> None:
    """Schedules upcoming events that are due based on total turns."""
    existing = await bot.database.settlement.get_active_events(user_id, server_id)
    existing_keys = {ev["event_key"] for ev in existing}

    for key, ev_def in SETTLEMENT_EVENTS.items():
        if key in existing_keys:
            continue  # Already active

        trigger_at = ev_def.get("trigger_at", [])
        rec_interval = ev_def.get("recurring_interval", 0)

        should_trigger = False
        if total_turns in trigger_at:
            should_trigger = True
        elif rec_interval > 0 and total_turns > 0:
            last_trigger = max((t for t in trigger_at if t <= total_turns), default=0)
            if last_trigger > 0:
                turns_since = total_turns - last_trigger
                if turns_since > 0 and turns_since % rec_interval == 0:
                    should_trigger = True

        if should_trigger:
            etype = ev_def.get("type", "instant")
            warning = ev_def.get("advance_warning_turns", 0)

            if etype == "upcoming" and warning > 0:
                await bot.database.settlement.add_event(
                    user_id, server_id, key, "upcoming",
                    turns_until=warning, turns_remaining=0,
                )
            elif etype == "ongoing":
                dur = ev_def.get("duration_turns", 3)
                await bot.database.settlement.add_event(
                    user_id, server_id, key, "ongoing",
                    turns_until=0, turns_remaining=dur,
                )
            elif etype == "instant":
                await _apply_event_effects(bot, user_id, server_id, ev_def)


# ---------------------------------------------------------------------------
# Black Market — value calculation + processing turns
# ---------------------------------------------------------------------------

def calculate_offer_value(
    offer: dict,
    tree_nodes: dict[str, int],
    bm_tier: int = 1,
) -> int:
    """
    Computes the total Value score for a Black Market offer.
    tree_nodes: {node_key: level} from bm_passive_tree.
    bm_tier: current Black Market building tier (1–5).
    """
    raw_value = sum(
        qty * BM_ITEM_VALUES.get(resource, 0)
        for resource, qty in offer.items()
        if qty > 0
    )

    # Value multiplier from BM tree (value branch)
    value_mult = 1.0
    for key in ("value_1", "value_2", "value_3"):
        if key in tree_nodes:
            bonuses = [0.05, 0.10, 0.15]
            idx = int(key.split("_")[-1]) - 1
            value_mult += bonuses[min(idx, len(bonuses) - 1)]

    return max(0, int(raw_value * value_mult))


def compute_processing_turns(
    value: int,
    bm_tier: int,
    tree_nodes: dict[str, int],
) -> int:
    """Returns the number of Development Turns required to process a deal."""
    raw = BM_TURNS_BASE + value / BM_TURNS_PER_VALUE

    # Tier reduction (T5 = −30%)
    tier_reduction = (bm_tier - 1) * 0.075  # 0% T1 → 30% T5
    raw *= max(0.0, 1.0 - tier_reduction)

    # Efficiency tree nodes
    eff_reductions = {"efficiency_1": 0.10, "efficiency_2": 0.20, "efficiency_3": 0.35}
    for key, red in eff_reductions.items():
        if key in tree_nodes:
            raw *= (1.0 - red)

    turns = max(1, int(raw))

    # Instant deals node: if ≤ 5 turns, complete immediately
    if "efficiency_4" in tree_nodes and turns <= 5:
        turns = 0

    return turns


# ---------------------------------------------------------------------------
# Black Market — reward rolling
# ---------------------------------------------------------------------------

def roll_bm_rewards(
    value: int,
    active_biases: list[str],
    player_level: int = 1,
    tree_nodes: dict | None = None,
) -> dict:
    """
    Rolls Black Market rewards for a completed deal.

    Returns a dict:
      {
        "gold": int,
        "currencies": {currency_key: qty},
        "items": [{"type": "weapon"|"armor"|etc., "level": int}],
        "eggs": int,
        "consume_parts": int,
        "summary_lines": [str],  # human-readable
      }
    """
    base_rolls = max(1, math.floor(value / BM_ROLLS_PER_VALUE))

    result: dict = {
        "gold": 0,
        "currencies": {},
        "items": [],
        "eggs": 0,
        "consume_parts": 0,
        "summary_lines": [],
    }

    categories = [c for c, _ in BM_BASE_LOOT_WEIGHTS]
    weights = [w for _, w in BM_BASE_LOOT_WEIGHTS]

    # Extra rolls from bias tree nodes — use the player's ACTUAL invested level
    _nodes = tree_nodes or {}
    extra_rolls: list[str] = []
    for bias_key in active_biases:
        node = BM_TREE_NODES.get(bias_key)
        if not node or node.get("branch") != "bias":
            continue
        invested_level = _nodes.get(bias_key, 0)
        if invested_level <= 0:
            continue  # not actually unlocked
        rolls_list = node.get("extra_rolls", [1])
        extra_count = rolls_list[min(invested_level - 1, len(rolls_list) - 1)]
        category = node.get("category", "rune")
        extra_rolls.extend([category] * extra_count)

    def _roll_category(cat: str) -> None:
        if cat == "gold":
            g = random.randint(BM_GOLD_MIN, BM_GOLD_MAX)
            result["gold"] += g

        elif cat == "rune":
            rune_pool = ["refinement_runes", "potential_runes", "shatter_runes", "imbue_runes"]
            rune_weights = [40, 40, 30, 10]
            chosen = random.choices(rune_pool, weights=rune_weights, k=1)[0]
            qty = random.randint(1, 5) if chosen != "imbue_runes" else random.randint(1, 2)
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + qty

        elif cat == "boss_key":
            key_pool = ["dragon_key", "angel_key", "soul_cores", "balance_fragment", "void_frags"]
            chosen = random.choice(key_pool)
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + 1

        elif cat == "gathering":
            mat_pool = [
                ("iron", 100), ("coal", 80), ("gold", 60), ("platinum", 40),
                ("oak_logs", 100), ("willow_logs", 80), ("mahogany_logs", 60),
                ("desiccated_bones", 100), ("regular_bones", 80), ("sturdy_bones", 60),
            ]
            chosen, qty_base = random.choice(mat_pool)
            qty = random.randint(qty_base // 2, qty_base)
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + qty

        elif cat == "essence":
            ess_pool = ["power", "protection", "insight", "evasion", "blocking", "deftness"]
            chosen = random.choice(ess_pool)
            result["currencies"][f"essence_{chosen}"] = result["currencies"].get(f"essence_{chosen}", 0) + random.randint(1, 3)

        elif cat == "gear":
            result["items"].append({"type": "random", "level": min(player_level, 100)})

        elif cat == "settler_mat":
            mat_pool = ["magma_core", "life_root", "spirit_shard"]
            chosen = random.choice(mat_pool)
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + random.randint(1, 2)

        elif cat == "egg":
            result["eggs"] += 1

        elif cat == "consume":
            result["consume_parts"] += 1

        elif cat == "curio":
            result["currencies"]["curios"] = result["currencies"].get("curios", 0) + 1

        elif cat == "high_end":
            pool = ["antique_tome", "pinnacle_key"]
            chosen = random.choices(pool, weights=[55, 45], k=1)[0]
            result["currencies"][chosen] = result["currencies"].get(chosen, 0) + 1

        elif cat == "guild_ticket":
            result["currencies"]["guild_ticket"] = result["currencies"].get("guild_ticket", 0) + random.randint(1, 2)

    # Base rolls
    for _ in range(base_rolls):
        cat = random.choices(categories, weights=weights, k=1)[0]
        _roll_category(cat)

    # Extra bias rolls
    for cat in extra_rolls:
        _roll_category(cat)

    # Build summary
    if result["gold"] > 0:
        result["summary_lines"].append(f"💰 {result['gold']:,} Gold")
    for cur, qty in result["currencies"].items():
        label = cur.replace("essence_", "Essence of ").replace("_", " ").title()
        result["summary_lines"].append(f"• {qty}× {label}")
    if result["items"]:
        result["summary_lines"].append(f"⚔️ {len(result['items'])}× Equipment Cache")
    if result["eggs"] > 0:
        result["summary_lines"].append(f"🥚 {result['eggs']}× Monster Egg")
    if result["consume_parts"] > 0:
        result["summary_lines"].append(f"🦴 {result['consume_parts']}× Body Part")

    return result


async def _grant_bm_rewards(bot, user_id: str, server_id: str, rewards: dict) -> None:
    """Applies a rolled BM reward dict to the player."""
    if rewards.get("gold", 0) > 0:
        await bot.database.users.modify_gold(user_id, rewards["gold"])

    for cur, qty in rewards.get("currencies", {}).items():
        if cur.startswith("essence_"):
            ess_type = cur[len("essence_"):]
            for _ in range(qty):
                await bot.database.essences.add(user_id, ess_type)
        elif cur in ("guild_ticket",):
            await bot.database.partners.add_tickets(user_id, qty)
        else:
            try:
                await bot.database.users.modify_currency(user_id, cur, qty)
            except Exception:
                pass

    for item_spec in rewards.get("items", []):
        try:
            from core.combat.economy.loot import (
                generate_accessory, generate_armor, generate_boot,
                generate_glove, generate_helmet, generate_weapon,
            )
            import random as _rnd
            slot = _rnd.choices(
                ["weapon", "armor", "accessory", "glove", "boot", "helmet"],
                weights=[35, 10, 25, 10, 10, 10], k=1
            )[0]
            ilvl = item_spec.get("level", 1)
            if slot == "weapon":
                item = await generate_weapon(user_id, ilvl, False)
                await bot.database.equipment.create_weapon(item)
            elif slot == "armor":
                item = await generate_armor(user_id, ilvl, False)
                await bot.database.equipment.create_armor(item)
            elif slot == "accessory":
                item = await generate_accessory(user_id, ilvl, False)
                await bot.database.equipment.create_accessory(item)
            elif slot == "glove":
                item = await generate_glove(user_id, ilvl)
                await bot.database.equipment.create_glove(item)
            elif slot == "boot":
                item = await generate_boot(user_id, ilvl)
                await bot.database.equipment.create_boot(item)
            elif slot == "helmet":
                item = await generate_helmet(user_id, ilvl)
                await bot.database.equipment.create_helmet(item)
        except Exception:
            pass

    for _ in range(rewards.get("eggs", 0)):
        try:
            await bot.database.eggs.add_egg(user_id, "normal")
        except Exception:
            pass

    for _ in range(rewards.get("consume_parts", 0)):
        try:
            import random as _rnd
            slots = ["head", "torso", "right_arm", "left_arm", "right_leg", "left_leg"]
            slot = _rnd.choice(slots)
            await bot.database.monster_parts.add_part(user_id, slot, "Unknown Creature", 1, 50)
        except Exception:
            pass
